clc; close all; clear;
songs_names = {'Dua Lipa - Physical';
    'Lady Gaga - Shallow';
    'George Michael - Careless Whisper';
    'Chaartaar - Ashoobam';
    'Distrubed - A Reason To Fight';
    'Breaking Benjamin - Give Me A Sign';
    'Pallett - Reng No.1';
    'Coldplay - Viva La Vida';
    'Avicci - Addicted To You';
    'Bon Jovi - You Give Love A Bad Name';
    'Imagine Dragons - Follow You';
    'Pink - Just Give Me A Reason';
    'Opeth - Benighted';
    'Hamed Nikpay - Disgraced(Rosva)';
    'Queen - We Will Rock You';
    'Homayoun Shajarian - Morghe Sahar';
    'Eminem - Mockingbird';
    'Alan Walker - Faded';
    'Jeff Buckley - Halleujah';
    'Godsmack - When Legends Rise';
    'Daal Band - Ham Avaz';
    'Manu Pilas - Bella Ciao';
    'Evanescence - Going Under';
    'Mohsen Namjoo - Toranj';
    'Farhad - Marde Tanha';
    'Metallica - Enter Sandman';
    'Adele - Skyfall';
    'Michael Giacchino - Married Life';
    'The Clash - Should I Stay or Should I Go';
    'Howard Shore - The Breaking of the FellowShip';
    'Sam Smith - Writing`s On the Wall';
    'Randy Newman - You`ve Got a Friend in Me';
    'John Legend - All Of Me';
    'Mohammad Esfahani - Oje Aseman';
    'Alireza Ghorbani - Arghavan';
    'ZAZ - Je Veux';
    'Amy Winehouse - Back to Black';
    'Sirvan Khosravi - Kojai To';
    'David Guetta/ Sia - Titanium';
    'Ali Azimi - Naakhoda';
    'Armin Van Bururen - Sth Real';
    'James Bay - Let It Go';
    'The Beatles - Here Comes The Sun';
    'Sara Naeini - Esharate Nazar';
    'Outlandish - Callin U';
    'Elton John - Your Song';
    'Billie Eilish - Lovley';
    'Mohammada Motamedi - Arame Man';
    'Salar Aghili - Che Begooyam';
    'Behnam Omran - Lantern'};

save('songs_names.mat','songs_names');